import "./globals.css";
import type { Metadata } from "next";
import { M_PLUS_1 } from "next/font/google";
const mplus1 = M_PLUS_1({ subsets: ["latin"] });

import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mplus1.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
